=== mattbuergler/pdp-simulator/schemadef/config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "sphereSchema": {
      "type": "object",
      "required": ["shape"],
      "properties": {
        "shape": {
          "type": "string",
          "enum": ["sphere"]
        },
        "size_distribution": {},
        "diameter": {
          "type": "number",
          "description": "The bubble diameter [m].",
          "exclusiveMinimum": 0.0
        },
        "mean_ln_diameter": {
          "type": "number",
          "description": "The mean of natural logarithm of the sphere-volume-equivalent bubble diameter [ln(m)]."
        },
        "sd_ln_diameter": {
          "type": "number",
          "description": "The standard deviation of the natural logarithm of the sphere-volume-equivalent bubble diameter [ln(m)]."
        }
      },
      "oneOf":[
        {
          "properties": {
            "size_distribution": {
              "const": "constant"
            }
          },
          "required": ["diameter"]
        },
        {
          "properties": {
           "size_distribution": {
              "const": "lognormal"
            }
          },
          "required": ["mean_ln_diameter","sd_ln_diameter"]
        }
      ]
    },
    "ellipsoidSchema": {
      "type": "object",
      "required": ["shape"],
      "properties": {
        "shape": {
          "type": "string",
          "enum": ["ellipsoid"]
        },
        "size_distribution": {},
        "diameter": {
          "type": "number",
          "description": "The sphere-volume-equivalent bubble diameter [m].",
          "exclusiveMinimum": 0.0
        },
        "mean_ln_diameter": {
          "type": "number",
          "description": "The mean of natural logarithm of the sphere-volume-equivalent bubble diameter [ln(m)]."
        },
        "sd_ln_diameter": {
          "type": "number",
          "description": "The standard of natural logarithm of the sphere-volume-equivalent bubble diameter [ln(m)]."
        },
        "aspect_ratio_type": {
          "description": "Type of aspect ratio: constant or dynamic (Aoyama et al. 2016)."
        },
        "aspect_ratio_value": {
          "type": "number",
          "description": "The aspect ratio, which is the ratio of the secondary bubble axis dimension to the primary bubble axis dimension [m].",
          "exclusiveMinimum": 0.0,
          "maximum": 1.0
        },
        "slip_velocity_ratio": {
          "type": "number",
          "description": "Ratio between bubble slip velocity and the main flow velocity [-]. Remark: This does not affect the bubble motion, but is only an assumpiton to calculate the bubble Reynold's number, which in turn is used to calculate the aspect ratio.",
          "exclusiveMinimum": 0.0,
          "maximum": 1.0,
          "default": 0.05
        }
      },
      "oneOf":[
        {
          "properties": {
            "size_distribution": {
              "const": "constant"
            }
          },
          "required": ["diameter"]
        },
        {
          "properties": {
           "size_distribution": {
              "const": "lognormal"
            }
          },
          "required": ["mean_ln_diameter","sd_ln_diameter"]
        }
      ],
      "oneOf":[
        {
          "properties": {
            "aspect_ratio_type": {
              "const": "constant"
            }
          },
          "required": ["aspect_ratio_value"]
        },
        {
          "properties": {
           "aspect_ratio_type": {
              "const": "Aoyama"
            }
          },
          "required": ["slip_velocity_ratio"]
        },
        {
          "properties": {
           "aspect_ratio_type": {
              "const": "Vakhrushev"
            }
          },
          "required": ["slip_velocity_ratio"]
        }
      ]
    }
  },
  "type": "object",
  "required": ["FLOW_PROPERTIES", "PROBE", "RECONSTRUCTION", "REPRODUCIBLE"],
  "optional": ["UNCERTAINTY_QUANTIFICATION"],
  "properties": {
    "FLOW_PROPERTIES": {
      "type": "object",
      "description": "Flow properties for generating the velocity time series.",
      "required": ["mean_velocity", "turbulent_intensity", "integral_timescale", "bubbles", "void_fraction", "realization_frequency", "duration"],
      "optional": ["ti_factor"],
      "properties": {
        "mean_velocity": {
          "type": "array",
          "description": "The mean flow velocity components (x,y,z) [m/s].",
          "minItems": 3,
          "maxItems": 3,
          "items": {
            "type": "number"
          }
        },
        "turbulent_intensity": {
          "type": "array",
          "description": "The (x,y,z) components of the turbulent intensity [-].",
          "minItems": 3,
          "maxItems": 3,
          "items": {
            "type": "number",
            "mininum": 0.0
          }
        },
        "ti_factor": {
          "type": "number",
          "description": "Factor for the turbulent intensity [-].",
          "default": 1.0
        },
        "shear_stress_corr_coeff": {
          "type": "array",
          "description": "The cross correlation coefficients of the xy-, xz-, and yz-shear-stress [-].",
          "minItems": 3,
          "maxItems": 3,
          "items": {
            "type": "number",
            "mininum": 0.0
          }
        },
        "integral_timescale": {
          "type": "array",
          "description": "The (x,y,z) components of the integral time scales [-].",
          "minItems": 3,
          "maxItems": 3,
          "items": {
            "type": "number",
            "exclusiveMinimum": 0.0
          }
        },
        "void_fraction": {
          "type": "number",
          "description": "The void fraction [-].",
          "minimum": 0.0,
          "maximum": 1.0
        },
        "duration": {
          "type": "number",
          "description": "Duration of the generated time series [s].",
          "exclusiveMinimum": 0.0
        },
        "realization_frequency": {
          "type": "number",
          "description": "Number of velocity realizations per second [Hz].",
          "exclusiveMinimum": 0.0
        },
        "bubbles": {
          "type": "object",
          "oneOf": [
              { "$ref":"#/definitions/sphereSchema"},
              { "$ref":"#/definitions/ellipsoidSchema"}
          ]
        }
      }
    },
    "PROBE": {
      "type": "object",
      "description": "The setup of the multi-tip probe.",
      "required": ["sampling_frequency", "sensors"],
      "properties": {
        "sampling_frequency": {
          "type": "number",
          "description": "The sampling frequency of the sensors [Hz].",
          "exclusiveMinimum": 0.0
        },
        "sensors": {
          "type": "array",
          "description": "Array containing the individual sensors.",
          "items": {
            "type": "object",
            "description": "This is a single sensor.",
            "required": ["id", "relative_location"],
            "properties": {
              "id": {
                "type": "number",
                "description": "The ID of the sensor."
              },
              "relative_location": {
                "type": "array",
                "description": "The (x,y,z) components of the relative sensor location [m].",
                "minItems": 3,
                "maxItems": 3,
                "items": {
                  "type": "number"
                }
              }
            }
          }
        }
      }
    },
    "RECONSTRUCTION": {
      "type": "object",
      "description": "Definitions regarding the reconstruction algorithm.",
      "required": ["type"],
      "optional": ["max_disparity"],
      "properties": {
        "type": {
          "type": "string",
          "description": "The reconstruction algorithm: Shen and Nakamura (2014), or Tian et al. (2015); or AWCC (Kramer et al., 2020).",
          "enum": ["Shen_Nakamura_2014", "Tian_et_al_2015", "dual_tip_AWCC","dual_tip_ED"]
        },
        "interface_pairing": {
          "type": "string",
          "description": "The interface-pairing signal processing algorithm: Shen et al. (2005); or Kramer et al. (2020).",
          "enum": ["Shen_et_al_2005", "Kramer_et_al_2020"]
        },
        "max_disparity": {
          "type": "number",
          "description": "Max. disparity threshold representing the confidence that the same bubble impacts both leading and trailing tips. Only required for algorithm of Kramer et al. (2020).",
          "minimum": 0.0
        },
        "n_particles": {
          "type": "number",
          "description": "The number of particles per averaging windows used for AWCC (Kramer et al., 2020).",
          "exclusiveMinimum": 0.0
        }
      },
      "oneOf":[
        {
          "properties": {
            "type": {
              "const": "Shen_Nakamura_2014"
            }
          },
          "required": ["interface_pairing","n_particles"]
        },
        {
          "properties": {
           "type": {
              "const": "Tian_et_al_2015"
            }
          },
          "required": ["interface_pairing","n_particles"]
        },
        {
          "properties": {
           "type": {
              "const": "dual_tip_AWCC"
            }
          },
          "required": ["n_particles"]
        },
        {
          "properties": {
           "type": {
              "const": "dual_tip_ED"
            }
          },
          "required": ["interface_pairing","n_particles"]
        }
      ]
    },
    "REPRODUCIBLE": {
      "type": "string",
      "description": "Define the reproducability of the process.",
      "enum": ["yes", "no"]
    },
    "UNCERTAINTY_QUANTIFICATION": {
      "type": "object",
      "description": "Module to account for uncertainties.",
      "optional": ["VIBRATION"],
      "properties": {
        "VIBRATION": {
          "type": "object",
          "description": "Vibrations of the probe induced by turbulent fluctuations and von Karman vortex shedding.",
          "required": ["frequencies","amplitudes"],
          "properties": {
            "frequencies": {
              "type": "array",
              "description": "The (x,y,z) vibration frequencies [Hz].",
              "minItems": 3,
              "maxItems": 3,
              "items": {
                "type": "number"
              }
            },
            "amplitudes": {
              "type": "array",
              "description": "The (x,y,z) vibration amplitudes [m].",
              "minItems": 3,
              "maxItems": 3,
              "items": {
                "type": "number"
              }
            }
          }
        }
      }
    }
  }
}

=== mattbuergler/pdp-simulator/tests/3_RA/B_Triangular_Tian/input/config.json
{
    "FLOW_PROPERTIES": {
        "mean_velocity":[5.0, 0.0, 0.0],
        "turbulent_intensity": [0.1, 0.05, 0.05],
        "shear_stress_corr_coeff": [0.0,-0.45,0.0],
        "integral_timescale": [0.01, 0.005, 0.005],
        "bubbles": {
            "shape": "sphere",
            "size_distribution": "constant",
            "diameter": 0.003
        },
        "void_fraction": 0.05,
        "duration": 10.0,
        "realization_frequency": 10000
    },
    "PROBE": {
        "sampling_frequency": 50000,
        "sensors": [
            {
                "id": 0,
                "relative_location":[
                    0.0,
                    0.0,
                    0.0
                ]
            },
            {
                "id": 1,
                "relative_location":[
                    0.001,
                    0.0,
                    0.0002
                ]
            },
            {
                "id": 2,
                "relative_location":[
                    0.001,
                    -0.0001,
                    -0.0001
                ]
            },
            {
                "id": 3,
                "relative_location":[
                    0.001,
                    0.0001,
                    -0.0001
                ]
            }
        ]
    },
    "RECONSTRUCTION": {
        "type": "Tian_et_al_2015",
        "interface_pairing": "Shen_et_al_2005",
        "n_particles": 10
    },
    "REPRODUCIBLE": "yes"
}
